# Generated by Django 3.0.5 on 2020-05-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=50)),
                ('Telephone', models.CharField(max_length=20)),
                ('Username', models.EmailField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Id', models.CharField(default='ID', max_length=50, null=True)),
                ('Customer', models.CharField(default='Customer', max_length=50, null=True)),
                ('Location', models.CharField(default='location', max_length=50, null=True)),
                ('Telephone', models.CharField(default='+233', max_length=50, null=True)),
                ('Product', models.CharField(max_length=50, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Final_Amount', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
                ('Invoice', models.CharField(max_length=50, null=True)),
                ('Payment', models.CharField(default='Pending', max_length=50)),
                ('Delivery', models.CharField(default='pending', max_length=50)),
                ('Date', models.DateField(auto_now_add=True, null=True)),
                ('Mobile_Number', models.CharField(default='+233', max_length=50, null=True)),
                ('Reg_Name', models.CharField(default='Agent Name', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Id', models.CharField(default='ID', max_length=50, null=True)),
                ('Customer', models.CharField(default='Customer', max_length=50, null=True)),
                ('Location', models.CharField(default='location', max_length=50, null=True)),
                ('Telephone', models.CharField(max_length=50, null=True)),
                ('Product', models.CharField(max_length=50, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Final_Amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Invoice', models.CharField(max_length=50, null=True)),
                ('Payment', models.CharField(default='Pending', max_length=50)),
                ('Delivery', models.CharField(default='Pending', max_length=50)),
                ('Date', models.DateField(auto_now_add=True, null=True)),
                ('Mobile_Number', models.CharField(default='0241209304', max_length=50, null=True)),
                ('Reg_Name', models.CharField(default='name', max_length=50, null=True)),
                ('Momo_CODE', models.CharField(default='273312', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer', models.CharField(max_length=50, null=True)),
                ('Location', models.CharField(max_length=50, null=True)),
                ('Telephone', models.CharField(max_length=50, null=True)),
                ('Amount_Paid', models.CharField(max_length=50, null=True)),
                ('Payment', models.CharField(default='Pending', max_length=50, null=True)),
                ('Delivery', models.CharField(default='Pending', max_length=50, null=True)),
                ('Date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(max_length=50, null=True)),
                ('Desc', models.CharField(max_length=300, null=True)),
                ('Quantity', models.IntegerField(null=True)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Image', models.ImageField(null=True, upload_to='Images')),
                ('Brand', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
