# Generated by Django 3.0.5 on 2020-06-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Customers', '0002_auto_20200601_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='DateTimeField',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='DateTimeField',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='Invoice',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
