# Generated by Django 3.0.5 on 2020-06-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Customers', '0003_auto_20200605_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='Onsubmitted',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='Onsubmitted',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
