# Generated by Django 3.0.5 on 2020-06-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Customers', '0004_auto_20200606_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Onsubmitted',
            field=models.CharField(default='Pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Onsubmitted',
            field=models.CharField(default='Pending', max_length=50, null=True),
        ),
    ]
