# Generated by Django 3.0.5 on 2020-06-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Customers', '0005_auto_20200606_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Onsubmitted',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
