# Generated by Django 3.0.5 on 2020-06-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Customers', '0006_auto_20200606_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='Mobile',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
