# Generated by Django 3.0.5 on 2020-06-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Customers', '0007_customerdetails_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='Firstname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='Lastname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='Location',
            field=models.CharField(max_length=510),
        ),
    ]
