# Generated by Django 3.0.5 on 2020-06-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Customers', '0008_auto_20200608_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='Email',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
