# Generated by Django 3.0.5 on 2020-06-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Customers', '0010_auto_20200615_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Availability',
            field=models.CharField(default='Available', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='Firstname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='Lastname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='Name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='Telephone',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='Delivery',
            field=models.CharField(default='pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='Mobile_Number',
            field=models.CharField(default='+233', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='Payment',
            field=models.CharField(default='Pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='Reg_Name',
            field=models.CharField(default='Agent Name', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Customer',
            field=models.CharField(default='Customer', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Customer_Id',
            field=models.CharField(default='ID', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Delivery',
            field=models.CharField(default='Pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Invoice',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Location',
            field=models.CharField(default='location', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Onsubmitted',
            field=models.CharField(default='Pending', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Payment',
            field=models.CharField(default='Pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Product',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Telephone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Amount_Paid',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Customer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Delivery',
            field=models.CharField(default='Pending', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Invoice',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Onsubmitted',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Payments',
            field=models.CharField(default='Pending', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Telephone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='Brand',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='Product',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
