# Generated by Django 3.0.5 on 2020-06-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Customers', '0011_auto_20200616_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Availability',
            field=models.CharField(choices=[('Available', 'Available'), ('Unvailable', 'Unavailable')], default='Available', max_length=200, null=True),
        ),
    ]
