# Generated by Django 3.0.5 on 2020-06-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Customers', '0013_auto_20200616_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Availability',
            field=models.CharField(default='Available', max_length=200, null=True),
        ),
    ]
