# Generated by Django 3.0.5 on 2020-06-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Customers', '0014_auto_20200616_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='Username',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
