# Generated by Django 3.0.5 on 2020-06-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Customers', '0015_auto_20200619_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='Location',
            field=models.CharField(max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='Mobile',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='Name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='Telephone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
