from django.contrib import admin
from django.urls import path
from . import views 

urlpatterns = [ 
     path('',views.HomePage, name='HomePage'),
    path('customer/',views.Customer, name='Customer'), 
    path('insert/',views.UserRegister, name='InsertCustomer'), 
    path('Login/',views.UserLogIn, name='Login'),
    path('Logout/',views.LogOut, name='Logout'),        
    path('Views/',views.ViewCustomer, name='Views'),
    path('Orders/',views.Orders, name='Orders'),
    path('Products/',views.GetProducts, name='Products'),   
    path('AddProducts/',views.AddProductData, name='GetProducts'),
    path('<int:id>/',views.AddProductData, name='AddProducts'),
    path('delete/<int:id>/',views.DeleteProduct, name='DeleteProducts'), 
    path('delete/',views.DeleteView, name='DelProducts'), 
    path('orderpicker/<int:id>',views.OrderPicker, name='OrderPicker'),  
    path('cart/',views.Cart, name='cart'),  
    path('viewcart/',views.CartViewer, name='viewcart'), 
    path('save/',views.SaveOrders, name='save'), 
    path('deletecart/<int:id>/',views.DeleteCart, name='deletecart'),  
    path('Time/',views.Time, name='Time'), 
    path('choose/',views.Options, name='options'),   
    path('OrderUpdate/',views.OrderUpdate, name='OrderUpdate'), 
    path('Dashboard/',views.Dashboard, name='Dashboard'), 
    path('Confirm/<int:id>/',views.ConfirmOrders, name='Confirm'), 
    path('Confirmation/',views.Confirmation, name='Confirmation'),  
    path('GeneratePdf/',views.GeneratePdf.as_view(), name='GeneratePdf'), 
    path('OrdersPdf/',views.OrdersPdf.as_view(), name='OrdersPdf'), 
    path('Success/',views.Success, name='Success'),  
    path('print/',views.Print, name='print'),   
    path('SMS/',views.SMS, name='SMS'),
    path('smsget/',views.SMSGet, name='smsget'),
    path('send/',views.SendSMS, name='send'),  
    path('OrderPrinter/',views.OrderPrinter, name='OrderPrinter'), 
    path('profile/',views.Profile, name='profile'),
    path('Eprofile/',views.EditProfile, name='Eprofile'),      
    path('corders/',views.ViewMyOrders, name='corders'),   
    path('reprint/<int:id>/',views.ReprintOrders, name='reprint'), 
    path('manage',views.ManageCustomers, name='manage'),   
    path('Ecustomer/<int:id>/',views.EditCustomer, name='Ecustomer'),
    path('contact/',views.ContactUS, name='contact'), 
    path('getcart/<int:id>',views.GetCart, name='getcart'),   
]

